package io.citybuddy.commerce.action;

public enum ActionRejectionReason {
  ACTION_VALIDATION_REJECTED,
  ACTION_CONCEALED_NOT_FOUND,
  ACTION_IDEMPOTENCY_INTENT_CONFLICT,
  ACTION_DURABLE_TRUTH_INCONSISTENT,
  ACTION_CONCURRENCY_OBSERVATION_INDETERMINATE,
  ACTION_DEPENDENCY_UNAVAILABLE
}
