"""Immutable contracts and bounds for stored support conversation evidence."""

from dataclasses import dataclass

SESSION_CONTEXT_POLICY_VERSION = "session-context-v1"


SESSION_CONTEXT_MAX_TURNS = 16


SESSION_CONTEXT_TOKEN_BUDGET = 6_144


MAX_USER_MESSAGE_CHARACTERS = 4000


MAX_ASSISTANT_MESSAGE_CHARACTERS = 256


SESSION_CONTEXT_MAX_CANDIDATE_TOKENS = SESSION_CONTEXT_MAX_TURNS * (
    8 + MAX_USER_MESSAGE_CHARACTERS * 4 + MAX_ASSISTANT_MESSAGE_CHARACTERS * 4
)


@dataclass(frozen=True)
class ConversationTurn:
    turn_id: str
    turn_sequence: int
    user_text: str
    assistant_text: str


@dataclass(frozen=True)
class ConversationHistory:
    turns: tuple[ConversationTurn, ...] = ()
    older_turns_available: bool = False


EMPTY_CONVERSATION_HISTORY = ConversationHistory()


@dataclass(frozen=True)
class AgentEvent:
    event_type: str
    payload: dict[str, object]


TOOL_BOUNDARY_FAILURE_REASONS = frozenset(
    {
        "ACTION_PREPARATION_IDENTITY_UNAUTHENTICATED",
        "ACTION_PREPARATION_IDENTITY_FORBIDDEN",
        "ACTION_PREPARATION_IDENTITY_UNAVAILABLE",
        "ACTION_PREPARATION_COMMERCE_VALIDATION_REJECTED",
        "ACTION_PREPARATION_COMMERCE_UNAUTHENTICATED",
        "ACTION_PREPARATION_COMMERCE_FORBIDDEN",
        "ACTION_PREPARATION_TARGET_NOT_FOUND",
        "ACTION_PREPARATION_INTENT_CONFLICT",
        "ACTION_PREPARATION_COMMERCE_UNAVAILABLE",
        "ACTION_PREPARATION_COMMERCE_TIMEOUT",
        "ACTION_PREPARATION_COMMERCE_INDETERMINATE",
        "ACTION_PREPARATION_RESPONSE_INVALID",
        "ACTION_PREPARATION_DURABLE_TRUTH_INCONSISTENT",
        "ACTION_SANDBOX_LIVENESS_UNAVAILABLE",
        "ACTION_SANDBOX_LIVENESS_REJECTED",
        "ACTION_SESSION_PERSISTENCE_UNAVAILABLE",
        "ACTION_REPLAY_PERSISTENCE_UNAVAILABLE",
        "ACTION_REFERENCE_PERSISTENCE_UNAVAILABLE",
        "ACTION_TURN_RESERVATION_PERSISTENCE_UNAVAILABLE",
        "ACTION_EXPIRY_PERSISTENCE_UNAVAILABLE",
        "ACTION_DECLINE_PERSISTENCE_UNAVAILABLE",
        "ACTION_CLARIFICATION_PERSISTENCE_UNAVAILABLE",
        "AGENT_TURN_COMPLETION_PERSISTENCE_UNAVAILABLE",
        "ACTION_CONFIRMATION_UNAVAILABLE",
        "ACTION_CONFIRMATION_IDENTITY_UNAUTHENTICATED",
        "ACTION_CONFIRMATION_IDENTITY_FORBIDDEN",
        "ACTION_CONFIRMATION_IDENTITY_UNAVAILABLE",
        "ACTION_CONFIRMATION_COMMERCE_VALIDATION_REJECTED",
        "ACTION_CONFIRMATION_COMMERCE_UNAUTHENTICATED",
        "ACTION_CONFIRMATION_COMMERCE_FORBIDDEN",
        "ACTION_CONFIRMATION_TARGET_NOT_FOUND",
        "ACTION_CONFIRMATION_INTENT_CONFLICT",
        "ACTION_CONFIRMATION_DURABLE_TRUTH_INCONSISTENT",
        "ACTION_CONFIRMATION_COMMERCE_UNAVAILABLE",
        "ACTION_CONFIRMATION_COMMERCE_TIMEOUT",
        "ACTION_CONFIRMATION_COMMERCE_INDETERMINATE",
        "ACTION_CONFIRMATION_RESPONSE_INVALID",
        "ACTION_CONFIRMATION_PERSISTENCE_UNAVAILABLE",
    }
)
