package io.citybuddy.commerce.refund;

public enum RefundRejectionReason {
  NOT_APPLICABLE,
  REFUND_CONCURRENCY_OBSERVATION_INDETERMINATE,
  REFUND_DURABLE_TRUTH_INCONSISTENT,
  REFUND_IDEMPOTENCY_INTENT_CONFLICT,
  REFUND_BUSINESS_CONFLICT,
  REFUND_DEPENDENCY_UNAVAILABLE,
  REFUND_CONCEALED_NOT_FOUND
}
