GRANT CREATE, REFERENCES ON commerce_db.* TO 'auth_migration'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, DROP, INDEX, REFERENCES, TRIGGER ON commerce_db.auth_schema_history TO 'auth_migration'@'%';
GRANT CREATE, ALTER, REFERENCES ON commerce_db.* TO 'commerce_migration'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, DROP, INDEX, REFERENCES, TRIGGER ON commerce_db.commerce_schema_history TO 'commerce_migration'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, DROP, INDEX, REFERENCES, CREATE VIEW, SHOW VIEW, TRIGGER ON cs_db.* TO 'agent_migration'@'%';
GRANT SELECT, INSERT, UPDATE ON commerce_db.auth_user_principal TO 'auth_app'@'%';
GRANT SELECT, INSERT, UPDATE ON commerce_db.auth_login_credential TO 'auth_app'@'%';
GRANT SELECT, INSERT, UPDATE ON commerce_db.auth_service_identity TO 'auth_app'@'%';
GRANT SELECT, INSERT, UPDATE ON commerce_db.auth_signing_key_metadata TO 'auth_app'@'%';
GRANT SELECT, INSERT, UPDATE ON commerce_db.crm_profile TO 'commerce_app'@'%';
GRANT SELECT, INSERT, UPDATE ON commerce_db.product TO 'commerce_app'@'%';
GRANT SELECT, INSERT, UPDATE ON commerce_db.catalog_metadata TO 'commerce_app'@'%';
GRANT SELECT, INSERT, UPDATE ON commerce_db.commerce_outbox TO 'commerce_app'@'%';
GRANT SELECT, INSERT ON commerce_db.standard_order TO 'commerce_app'@'%';
GRANT UPDATE ON commerce_db.standard_order TO 'commerce_app'@'%';
GRANT SELECT, INSERT, UPDATE ON commerce_db.mock_payment_attempt TO 'commerce_app'@'%';
GRANT SELECT, INSERT ON commerce_db.mock_payment_callback TO 'commerce_app'@'%';
GRANT SELECT, INSERT, UPDATE ON commerce_db.order_idempotency TO 'commerce_app'@'%';
GRANT SELECT, INSERT, UPDATE ON commerce_db.seckill_activity TO 'commerce_app'@'%';
GRANT SELECT, INSERT, UPDATE ON commerce_db.seckill_reservation TO 'commerce_app'@'%';
GRANT SELECT, INSERT, UPDATE ON commerce_db.seckill_order TO 'commerce_app'@'%';
GRANT SELECT, INSERT ON commerce_db.inventory_ledger TO 'commerce_app'@'%';
GRANT SELECT, INSERT, UPDATE ON commerce_db.mock_refund TO 'commerce_app'@'%';
GRANT SELECT, INSERT ON cs_db.support_session TO 'agent_app'@'%';
GRANT SELECT, INSERT, UPDATE ON cs_db.support_conversation TO 'agent_app'@'%';
GRANT SELECT, INSERT, UPDATE ON cs_db.support_turn TO 'agent_app'@'%';
GRANT SELECT, INSERT ON cs_db.support_event TO 'agent_app'@'%';
GRANT SELECT, INSERT ON cs_db.support_feedback TO 'agent_app'@'%';
GRANT SELECT, INSERT ON cs_db.retrieval_decision TO 'agent_app'@'%';
GRANT SELECT, INSERT ON cs_db.retrieval_evidence TO 'agent_app'@'%';
GRANT SELECT, INSERT, UPDATE ON commerce_db.auth_eval_test_principal TO 'auth_app'@'%';
GRANT SELECT, INSERT, UPDATE ON commerce_db.eval_sandbox TO 'commerce_app'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON commerce_db.eval_sandbox_product_fixture TO 'commerce_app'@'%';
GRANT SELECT, INSERT ON commerce_db.eval_sandbox_effect_stub TO 'commerce_app'@'%';
GRANT SELECT, INSERT ON commerce_db.eval_commerce_audit_reference TO 'commerce_app'@'%';
GRANT SELECT, INSERT ON commerce_db.eval_commerce_product_observation TO 'commerce_app'@'%';
GRANT SELECT ON commerce_db.eval_commerce_audit_legacy_watermark TO 'commerce_app'@'%';
GRANT SELECT ON commerce_db.eval_commerce_audit_reference TO 'commerce_migration'@'%';
GRANT INSERT ON commerce_db.eval_commerce_audit_legacy_watermark TO 'commerce_migration'@'%';
REVOKE IF EXISTS SELECT ON commerce_db.eval_commerce_audit_reference FROM 'commerce_migration'@'%';
REVOKE IF EXISTS INSERT ON commerce_db.eval_commerce_audit_legacy_watermark FROM 'commerce_migration'@'%';
GRANT SELECT, INSERT, UPDATE ON commerce_db.faq_source TO 'commerce_app'@'%';
GRANT SELECT, INSERT ON commerce_db.faq_publication_command TO 'commerce_app'@'%';
