package io.citybuddy.commerce.payment;

public enum MockPaymentRejectionReason {
  NOT_APPLICABLE,
  DIRECT_USER_AUTHORIZATION_REJECTED,
  EVALUATION_COMPONENT_UNAVAILABLE,
  COMMITTED_PAYMENT_TRUTH_INCONSISTENT,
  IDEMPOTENCY_INTENT_CONFLICT,
  ORDER_NOT_ELIGIBLE,
  CONCEALED_NOT_FOUND,
  SANDBOX_NOT_ACTIVE,
  DEPENDENCY_OBSERVATION_INDETERMINATE
}
